name: WeChat Bot Notification

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '15 13 * * *'  # 每天 UTC 13:30，即北京时间 21:30
  workflow_dispatch:       # 手动触发也可以用

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send WeChat Message
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=eb2eefa5-081f-4d51-a761-9aa057ad024a' \
            -H 'Content-Type: application/json' \
            -d '
            {
                "msgtype": "text",
                "text": {
                    "content": "@所有人 晚上好🌙，记得到哔哩哔哩平台进行点赞和互动哟～ 
                    \n1️⃣ 👉 [【📥 Tuistash - Logstash 实时监控，告别图形界面，高效便捷！】](https://www.bilibili.com/video/BV1FpGXzaEcq/?share_source=copy_web&vd_source=1c09a7c3bd9abce39b9d4a556c1e4410) 
                    \n2️⃣ 👉 [【📥 bmm - 告别书签混乱，让你闪电直达！】](https://www.bilibili.com/video/BV1MKVLzrEt4/?share_source=copy_web&vd_source=1c09a7c3bd9abce39b9d4a556c1e4410)"
                }
            }'

