name: "test1"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "push message"
        run: echo ${{ github.job.name }}  ${{ github.job }} ${{ env.GITHUB_RUN_ID }}    