name: Build on Ubuntu
#on: push

jobs:
  build:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq